// 100 frases motivacionales / bonitas que el footer muestra de forma aleatoria.
export const FRASES = [
  "Tú puedes con esto y con mucho más.",
  "Cada día es una nueva oportunidad.",
  "Sigue adelante, vas muy bien.",
  "Los grandes sueños empiezan con pequeños pasos.",
  "Hoy es un buen día para brillar.",
  "Confía en ti, lo estás haciendo genial.",
  "El esfuerzo de hoy es el éxito de mañana.",
  "Nunca subestimes lo lejos que has llegado.",
  "Lo mejor está por venir.",
  "Tu trabajo vale, y mucho.",
  "Paso a paso se llega lejos.",
  "Cree en ti incluso cuando nadie más lo haga.",
  "La constancia siempre da frutos.",
  "Eres más fuerte de lo que crees.",
  "Haz que hoy cuente.",
  "Tus ganas mueven montañas.",
  "Pequeños avances también son avances.",
  "El que persevera, alcanza.",
  "Sonríe, lo estás logrando.",
  "Cada venta es una semilla de tu sueño.",
  "Lo difícil de hoy te hace fuerte mañana.",
  "Tu esfuerzo nunca es en vano.",
  "Confía en el proceso.",
  "Hoy mejor que ayer.",
  "Las cosas buenas toman tiempo.",
  "Sé constante y verás resultados.",
  "Tu actitud define tu altura.",
  "Cree, crea y crece.",
  "Nada grande se construye en un día.",
  "Tu negocio crece con cada decisión.",
  "Atrévete a ir por más.",
  "El límite lo pones tú.",
  "Sigue, que vas por buen camino.",
  "La disciplina te lleva donde la motivación no llega.",
  "Hazlo con amor y se notará.",
  "Eres capaz de cosas increíbles.",
  "Un día a la vez, un paso a la vez.",
  "Tu dedicación inspira.",
  "Levántate y vuelve a intentarlo.",
  "El éxito es la suma de pequeños esfuerzos.",
  "Florece donde estás plantado.",
  "Hoy siembras, mañana cosechas.",
  "Tu esfuerzo de hoy es tu orgullo de mañana.",
  "Que nada apague tus ganas.",
  "Lo estás haciendo mejor de lo que crees.",
  "Persigue tus metas con el corazón.",
  "Cada cliente es una oportunidad de brillar.",
  "Sé la mejor versión de ti hoy.",
  "El trabajo duro vence al talento.",
  "Mantén el enfoque y avanza.",
  "Tus sueños merecen tu esfuerzo.",
  "Confía: vas a lograrlo.",
  "Hoy puede ser el mejor día.",
  "Tu pasión es tu motor.",
  "No te rindas, casi lo logras.",
  "Cada esfuerzo suma.",
  "Crece con calma, pero crece.",
  "Tú decides qué tan lejos llegas.",
  "Lo imposible solo tarda un poco más.",
  "Haz hoy lo que tu yo del futuro agradecerá.",
  "El progreso es progreso, sin importar el tamaño.",
  "Brilla con luz propia.",
  "Tu constancia es tu superpoder.",
  "Sé valiente, los resultados llegan.",
  "Pon el alma en lo que haces.",
  "Hoy también es para ti.",
  "Convierte los retos en logros.",
  "Tu actitud positiva contagia.",
  "Avanza aunque sea despacio.",
  "Cada número cuenta una historia de esfuerzo.",
  "Tú eres el corazón de tu negocio.",
  "El primer paso ya lo diste.",
  "La paciencia también es trabajo.",
  "Confía en tu camino.",
  "Hazlo simple, hazlo bien.",
  "Tus metas están más cerca de lo que piensas.",
  "El que no se rinde, gana.",
  "Hoy es tu día para crecer.",
  "Tu esfuerzo deja huella.",
  "Cree en lo que estás construyendo.",
  "Pequeño hoy, grande mañana.",
  "Tú marcas la diferencia.",
  "Sigue soñando y trabajando.",
  "La mejor inversión es creer en ti.",
  "Cada logro empezó con una decisión.",
  "Mantente firme, vas bien.",
  "Tu dedicación vale oro.",
  "Hoy es un buen día para empezar de nuevo.",
  "Disfruta el camino, no solo la meta.",
  "Tu trabajo construye tu futuro.",
  "Lo lograrás, paso a paso.",
  "Que tu esfuerzo siempre tenga sentido.",
  "Eres más capaz de lo que imaginas.",
  "Apuesta por ti, siempre.",
  "La suerte favorece a quien insiste.",
  "Avanza con confianza.",
  "Tu sonrisa es tu mejor herramienta.",
  "Hoy también vas a lograrlo.",
  "Crece, aprende y vuelve a intentarlo.",
  "Tu historia se escribe con esfuerzo.",
  "Gracias por dar siempre lo mejor de ti.",
];
